export class User{
    ID?:number;
    firstName?:String;
    lastName?:String;
    suffix?:String;
    faName?:String;
    faOccu?:String;
    maName?:String;
    maOccu?:String;
    pHouse?:String;
    proad?:String;
    pPolice?:String;
    pPost?:String;
    pPostCode?:String;
    pDistrict?:String;
    pCountry?:String;
    mNumber?:String;
    pNumber?:String;
    email?:String;
    gender?:String;
    religion?:String;
    nationality?:String;
}